version: '3'

services:
  face-detection-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartroads-ai-face-detection-app
    ports:
      - "8000:8000"
      - "8501:8501"
    restart: unless-stopped